<div id="test-accordion" data-mage-init='{
        "accordion":{
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}'>
    <h3>Accordion widget</h3>
    <div data-role="collapsible">
        <h4 data-role="trigger">
            <span>Title 1</span>
        </h4>
    </div>
    <div data-role="content">Personal information provided on the website and online credit card transactions are
        transmitted through a secure server. We are committed to handling your personal information with high standards
        of information security. We take appropriate physical, electronic, and administrative steps to maintain the
        security and accuracy of personally identifiable information we collect, including limiting the number of people
        who have physical access to our database servers, as well as employing electronic security systems and password
        protections that guard against unauthorized access.
    </div>

    <div data-role="collapsible">
        <h4 data-role="trigger">
            <span>Title 2</span>
        </h4>
    </div>
    <div data-role="content">Personal information provided on the website and online credit card transactions are
        transmitted through a secure server. We are committed to handling your personal information with high standards
        of information security. We take appropriate physical, electronic, and administrative steps to maintain the
        security and accuracy of personally identifiable information we collect, including limiting the number of people
        who have physical access to our database servers, as well as employing electronic security systems and password
        protections that guard against unauthorized access.
    </div>

    <div data-role="collapsible">
        <h4 data-role="trigger">
            <span>Title 3</span>
        </h4>
    </div>
    <div data-role="content">Personal information provided on the website and online credit card transactions are
        transmitted through a secure server. We are committed to handling your personal information with high standards
        of information security. We take appropriate physical, electronic, and administrative steps to maintain the
        security and accuracy of personally identifiable information we collect, including limiting the number of people
        who have physical access to our database servers, as well as employing electronic security systems and password
        protections that guard against unauthorized access.
    </div>
</div>

<div data-mage-init='{
    "collapsible":{
        "animate":{ "duration" :1000, "easing":"easeOutCubic"}
    }}'>
    <h3>Collapsible widget here</h3>
    <div data-role="title">
        <h4>Exams</h4>
    </div>
    <div data-role="content">
        <ul>
            <li>Maths</li>
            <li>English</li>
            <li>Science</li>
        </ul>
    </div>
</div>
